---
output:
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: !expr here::here("svm-latex-ms.tex")
    highlight: pygments
header-includes:
  - \usepackage{hyperref}
  - \usepackage{array}
  - \usepackage{caption}
  - \usepackage{graphicx}
  - \usepackage{siunitx}
  - \usepackage[table]{xcolor}
  - \usepackage{multirow}
  - \usepackage{hhline}
  - \usepackage{calc}
  - \usepackage{tabularx}
  - \usepackage{fontawesome}
  - \usepackage[para,online,flushleft]{threeparttable}
  - \usepackage{amsmath}
  - \usepackage{amsfonts}
  - \usepackage{amssymb}
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \setlength{\parindent}{0pt}
  - \setlength{\parskip}{1em}
biblio-style: apsr
title: "`r paste('Daily Reading', params$date, sep = ' ')`"
author:
- name: "`r paste(params$author)`"
  affiliation: Grace Church Waco
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: libertine
fontsize: 11pt
endnote: no
params:
  date: "November 03, 2025"
  author: "Carson Slater"
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(
  dev = "cairo_pdf",
  fig.width = 5,
  fig.height = 5,
  fig.align = 'center',
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  results = 'markup'
)

theme_set(theme_minimal(base_family = "Roboto Condensed"))
```


## Reading Through the Bible (Ezekiel 1-2)

<!-- Note what you are reading today, characters, themes, a summary of the narrative, any useful context, etc. -->

The setting of Ezekiel is in the fifth exile of King Jehoiachin of Judah to Babylon in 597 BC. Ezekiel, a priest and prophet, is among the exiles. The book opens with a dramatic vision of God's glory, symbolized by a chariot-like throne borne by four living creatures, each with four faces and wings. It seems to parallel the four living creatures in Revelation. In chapter 2, Ezekiel is called by God, and told to stand up to speak with God. God commissions Ezekiel to be a prophet to the rebellious house of Israel and to not be afraid of their words. For he is to merely be a prophet, that the people of Israel will know that he is a prophet, even if they do not listen to him. Chapter 2 concludes with a scroll being handed to Ezekiel, on the front and back of which he says is "lamentations, mourning, and woe."

## Psalm 106

<!-- Note what you read today, and what the Psalm/Proverb was saying. Note how it ministered to you. -->

<!-- Alternate between Psalms and Proverbs each month (or morning?!) -->

\begin{quote}
  Blessed are they who observe justice,
  who do righteousness at all times!\footnote{Psalm 106:3 ESV}
\end{quote}

This Psalm is a really cool Psalm, as it has lots of allusions to Israel escaping Egypt and wandering in the wilderness. It recounts the many ways that Israel disobeyed, as well as God's utter faithfulness to them. God always remembers his covenants with his people.

\begin{quote}
  Save us, O Lord our God and gather us from among the nations, that we may give thanks to your holy name and glory in your praise.

  Blessed be the Lord, the God of Israel, from everlasting to everlasting! And let all the people say, "Amen!" Praise the Lord!\footnote{Psalm 106:47-48 ESV}
\end{quote}

Also -- an epic way to end a Psalm.

## Deep Dive

Chambers stated, "Impatience means unbelief in God's providence." He notes this after noting that this word of God to Ezekiel came five years into captivity. It was not immediate, nor was it what many in our microwave culture would expect. Chambers advocates for a sentiment similar to Eugene Peterson's "long obedience in the same direction." Instead of jumping into what he calls "practical work," Chambers encourages us to wait on God, to trust in His timing, and to be obedient in the small things while we wait.

Additionally, Chambers notes a few other things. (1) God uses Ezekiel's bereavement to empower him to represent God to his people. (2) "There is no call of God to be prosperous, but to be a proclaimer of God's truth unto the gates of death."

<!-- Break out an extrabiblical text or commentary on the text you are reading. Note what you learned from this deeper study. -->

<!-- ## Notes -->

<!-- ## Other Thoughts -->

<!-- ## Prayers -->
